---
- hosts: all
  vars_files:
    - ../secrets/unibo_login.yml
  tasks:
  #https://github.com/ansible/ansible-modules-core/issues/2951#issuecomment-191892885 absolute state of ansible
    - name: update
      shell: apt-get update
    - name: install stuff
      apt:
         pkg:
             #             - dbus-x11
             - pulseaudio
             - pulseaudio-utils
             - pulsemixer
             - tmux
             - nodejs
             - npm
             - libnss3
             - ffmpeg
             - xvfb
             - xfce4
             - libgbm-dev
             - imagemagick
    - name: install chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - name: user yolo
      user:
        name: yolo
        shell: /bin/bash
        groups: audio,sudo,voice,users,staff
        uid: 1666 
        append: yes
    - name: crea cartella puppeteer
      file:
        path: /home/yolo/pup
        state: directory
        owner: yolo
        group: yolo
        mode: '0777'
        recurse: yes
    - name: install puppeter
      npm:
        name: puppeteer
        path: /home/yolo/pup
      become: true
      become_user: yolo
    - name: copy pup test script
      copy:
        dest: /home/yolo/pup/ytTest.js
        src: ../puppeteer/ytTest.js
        owner: yolo
        group: yolo
        mode: '0666'
    - name: copy pup script
      template:
        dest: /home/yolo/pup/teamsTest.js
        src: ../puppeteer/teamsTest.js.j2
        owner: yolo
        group: yolo
        mode: '0666'
    - name: cambia permessi xdg_runtime
      file:
        path: /run/user/0
        state: directory
        owner: 1666
        group: 1666
        mode: '0777'
        recurse: yes
    - name: tmux start recording
      shell:
        cmd: tmux new-session \; send-keys 'touch /root/started; su -c "pulseaudio -v" yolo -' C-m \; new-session \; send-keys 'xvfb-run --listen-tcp -s "-ac -screen 0 1920x1080x24" su -c "node /home/yolo/pup/{{ test }}.js" yolo -' C-m \; split-window -v \; send-keys 'su -c "ffmpeg -y -f pulse -ac 2 -i "auto_null.monitor" -framerate 15 -f x11grab -draw_mouse 0 -s 1920x1080 -i :99 -c:v libx265 -crf 35 -preset medium /home/yolo/reg.mkv" yolo -' C-m \; detach 
        creates: /root/started
      ignore_errors: yes
# would be very nice if this worked, but it doesnt
#    - name: copy rc.xvfb
#      copy:
#        src: ./stuff/rc.xvfb-pup
#        dest: /usr/local/sbin/rc.xvfb-pup
#        mode: '0777'
#    - name: copy rc.ffmpeg
#      copy:
#        src: ./stuff/rc.ffmpeg-rec 
#        dest: /usr/local/sbin/rc.ffmpeg-rec
#        mode: '0777'
#    - name: start xvfb
#      command:
#        cmd: "/usr/local/sbin/rc.xvfb-pup start"
#        creates: /var/run/xvfb-pup.pid
#    - name: start ffmpeg
#      command:
#        cmd: "/usr/local/sbin/rc.ffmpeg-rec start"
#        creates: /var/run/ffmpeg-rec.pid
