---
- hosts: all
  vars_files:
    - ../secrets/unibo_login.yml
  tasks:
    - name: change mirrors
      template:
        src: templates/sources.list.debian
        dest: /etc/apt/sources.list

    # https://github.com/ansible/ansible-modules-core/issues/2951#issuecomment-191892885
    # absolute state of ansible
    - name: update
      shell: apt-get -y update
      args:
        warn: false
    - name: install required packages
      apt:
        pkg:
          # - dbus-x11
          - pulseaudio
          - pulseaudio-utils
          - pulsemixer
          - tmux
          - nodejs
          - npm
          - libnss3
          - ffmpeg
          - xvfb
          - xfce4
          - libgbm-dev
          - imagemagick
    - name: install chrome
      apt:
        deb: "https://dl.google.com/linux/direct/\
            google-chrome-stable_current_amd64.deb"
    - name: user yolo
      user:
        name: yolo
        shell: /bin/bash
        groups: [audio,sudo,voice,users,staff]
        uid: 1666
        append: true
    - name: create puppeteer directory
      file:
        path: /home/yolo/pup
        state: directory
        owner: yolo
        group: yolo
        mode: '0777'
        recurse: true
    - name: install puppeter
      npm:
        name: puppeteer
        path: /home/yolo/pup
      become: true
      become_user: yolo
    - name: copy pup script
      template:
        dest: /home/yolo/pup/teams.js
        src: ./scripts/teams.js
        owner: yolo
        group: yolo
        mode: '0666'
    - name: Upload directly to Telegram
      block:
        - name: Include Telegram api id and hash
          include_vars:
            file: ../secrets/telegram_api.yml
        - name: Install pip3
          apt:
            name:
              - python3-pip
        - name: install python libs
          pip:
            name:
              - telethon
              - asyncio
        - name: Upload telegram script and session
          template:
            src: ./scripts/{{item}}
            dest: /home/yolo/{{item}}
            owner: yolo
            group: yolo
            mode: '0777'
          loop:
            - lezioni-carica-telegram.py
            - send.sh
            - anon.session
            - materie.txt
      when: telegram | bool
    - name: change xdg_runtime permissions
      file:
        path: /run/user/0
        state: directory
        owner: '1666'
        group: '1666'
        mode: '0777'
        recurse: true
    - name: execute recording script
      script:
        cmd: ./scripts/record.sh {{ pupscript }}
